// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllerCommand } from "./controller/command";
import type { SequencerCommand } from "./sequencer/command";

export type Command =
  | { type: "HealthCheck" }
  | { type: "SequencerCommand"; content: SequencerCommand }
  | { type: "ControllerCommand"; content: ControllerCommand };
