// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllerCommand } from "./controller/command";

export type Command = { "type": "HealthCheck" } | { "type": "ControllerCommand", content: ControllerCommand, };