name: test
run-name: "testing `${{github.event.head_commit.id}}: ${{github.event.head_commit.message}}"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - name: build
      run: cargo build --verbose
      working-directory: ./src-tauri
    - name: test
      run: cargo test --verbose
      working-directory: ./src-tauri
