name: test
run-name: "testing `${{github.event.head_commit.id}}: ${{github.event.head_commit.message}}"

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
